@extends('layouts.app')
@section('title', $client->displayName().' — Financeiro')
@section('content')
@include('finance._nav')
<section class="page-heading"><div><div class="page-eyebrow"><span class="status-dot"></span>Cliente · Financeiro</div><h1>{{ $client->displayName() }}</h1><p>Recorrência, faturas e pagamentos em um só lugar.</p></div><div class="page-actions">
@if($primary)<a class="button button-secondary" href="{{ route('finance.contracts.edit',$primary) }}">Editar configuração</a>@else<a class="button button-primary" href="{{ route('finance.contracts.create',['client_id'=>$client->id,'return_to_client'=>1]) }}">Configurar cobrança recorrente</a>@endif
<a class="button button-primary" href="{{ route('finance.invoices.create',['client_id'=>$client->id]) }}">Nova cobrança avulsa</a><a class="button button-secondary" href="{{ route('finance.invoices.index',['search'=>$client->client_code]) }}">Ver faturas</a></div></section>
@if(session('success'))<div class="alert-success">{{ session('success') }}</div>@endif
<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Cobrança recorrente</span><h2>{{ $primary?->items->first()?->description ?: 'Sem cobrança recorrente' }}</h2></div>@if($primary)<span class="status-pill {{ $primary->status==='active'?'is-active':'is-inactive' }}">{{ $primary->status==='active'?'Ativo':'Inativo' }}</span>@endif</header>
@if(!$primary)<div class="empty-state"><div><strong>Nenhuma recorrência configurada</strong><span>Configure item, valor, geração e vencimento para este cliente.</span></div></div>
@else @php($total=$primary->items->where('active',true)->sum(fn($item)=>(float)$item->quantity*(float)$item->unit_amount))
<div class="finance-recurring-grid"><div><span>Item/serviço</span><strong>{{ $primary->items->first()?->description ?: 'Requer configuração' }}</strong></div><div><span>Valor</span><strong>R$ {{ number_format($total,2,',','.') }} / mês</strong></div><div><span>Geração</span><strong>Todo dia {{ $primary->generation_day }}</strong></div><div><span>Vencimento</span><strong>Dia {{ $primary->due_day }}</strong></div><div><span>Método</span><strong>Boleto + Pix</strong></div><div><span>Destinatário</span><strong>{{ $recipient ?: 'Contato financeiro' }}</strong></div><div><span>Automação de geração</span><strong>{{ $automationEnabled?'Automática':'Desligada' }}</strong></div><div><span>Operação</span><strong>{{ $automationEnabled?'Automática':'Manual' }}</strong></div></div>
@if($primary->status==='active' && auth()->user()->isAdministrator())<form method="POST" action="{{ route('finance.contracts.suspend',$primary) }}" class="form-actions">@csrf<button class="button button-secondary">Suspender cobrança recorrente</button></form>@endif
@endif</section>
@if($previous->isNotEmpty())<details class="panel finance-history"><summary>Configurações anteriores ({{ $previous->count() }})</summary><div class="table-responsive"><table class="data-table"><thead><tr><th>Item</th><th>Geração</th><th>Vencimento</th><th>Status</th><th></th></tr></thead><tbody>@foreach($previous as $contract)<tr><td>{{ $contract->items->first()?->description ?: 'Sem item' }}</td><td>Dia {{ $contract->generation_day }}</td><td>Dia {{ $contract->due_day }}</td><td>{{ match($contract->status){'active'=>'Ativo','suspended'=>'Suspenso','ended'=>'Encerrado',default=>'Inativo'} }}</td><td><a href="{{ route('finance.contracts.show',$contract) }}">Abrir</a></td></tr>@endforeach</tbody></table></div></details>@endif
<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Movimentação</span><h2>Faturas recentes</h2></div></header>@if($invoices->isEmpty())<div class="empty-state"><div><strong>Nenhuma fatura</strong><span>As primeiras faturas aparecerão aqui.</span></div></div>@else<div class="table-responsive"><table class="data-table"><thead><tr><th>Fatura</th><th>Emissão</th><th>Vencimento</th><th>Valor</th><th>Status</th></tr></thead><tbody>@foreach($invoices as $invoice)@php($charge=$invoice->charges->first())<tr><td><a href="{{ route('finance.invoices.show',$invoice) }}">#{{ $invoice->id }}</a></td><td>{{ $invoice->issued_on?->format('d/m/Y') }}</td><td>{{ $invoice->due_on?->format('d/m/Y') }}</td><td>R$ {{ number_format((float)$invoice->total,2,',','.') }}</td><td>{{ match($charge?->status ?: $invoice->status){'paid'=>'Pago','overdue'=>'Vencido','canceled'=>'Cancelado','submission_unknown','failed','submitting'=>'Requer atenção',default=>'Aguardando pagamento'} }}</td></tr>@endforeach</tbody></table></div>@endif</section>
@if(auth()->user()->isAdministrator() && $primary)<details class="panel finance-technical"><summary>Detalhes técnicos</summary><dl class="details-list"><div><dt>Referência interna</dt><dd class="table-mono">{{ $primary->public_id }}</dd></div><div><dt>Configurações cadastradas</dt><dd>{{ $previous->count()+1 }}</dd></div><div><dt>Automação externa</dt><dd>{{ $automationEnabled?'Habilitada':'Desabilitada' }}</dd></div></dl></details>@endif
@endsection
