@extends('layouts.app')
@section('title','Novo agendamento — IRCENTER')
@section('content')
<div class="page-header"><div><span class="eyebrow">Agenda</span><h1>Novo agendamento</h1><p>Criação manual com disponibilidade revalidada no servidor.</p></div></div>
@include('scheduling.admin.nav')
<section class="panel scheduling-create"><form method="post" action="{{ route('scheduling.admin.appointments.store') }}" class="stack-form">@csrf
<label for="event_type_id">Tipo de agendamento<select id="event_type_id" name="event_type_id" required><option value="">Selecione</option>@foreach($eventTypes as $type)<option value="{{ $type->id }}" data-url="{{ route('scheduling.admin.appointments.availability',$type) }}">{{ $type->name }} — {{ $type->duration_minutes }} min</option>@endforeach</select></label>
<div class="form-pair"><label for="admin-date">Data<input id="admin-date" type="date" required></label><label for="admin-timezone">Timezone<input id="admin-timezone" name="timezone" value="{{ $timezone }}" required></label></div>
<fieldset><legend>Horários disponíveis</legend><div id="admin-slots" class="booking-slots" aria-live="polite"><p class="empty-state">Selecione tipo e data.</p></div></fieldset><input type="hidden" name="start" id="admin-start" required>
<div class="form-pair"><label>Participante<input name="guest_name" value="{{ old('guest_name') }}" required maxlength="120"></label><label>E-mail<input type="email" name="guest_email" value="{{ old('guest_email') }}" required maxlength="255"></label></div>
<label>Cliente associado<select name="client_id"><option value="">Sem associação</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->displayName() }}</option>@endforeach</select></label>
<div class="form-pair"><label>Telefone (opcional)<input name="guest_phone" maxlength="40"></label><label>Empresa (opcional)<input name="guest_company" maxlength="120"></label></div><label>Observações (opcional)<textarea name="notes" maxlength="2000"></textarea></label>
@if($errors->any())<div class="alert alert-danger" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<button class="button button-primary" id="admin-submit" disabled>Criar agendamento</button></form></section>
@endsection
@push('scripts')<script nonce="{{ request()->attributes->get('csp_nonce') }}">(()=>{const type=document.querySelector('#event_type_id'),date=document.querySelector('#admin-date'),zone=document.querySelector('#admin-timezone'),slots=document.querySelector('#admin-slots'),start=document.querySelector('#admin-start'),submit=document.querySelector('#admin-submit');async function load(){start.value='';submit.disabled=true;if(!type.value||!date.value)return;slots.innerHTML='<p>Carregando horários…</p>';try{const url=new URL(type.selectedOptions[0].dataset.url,location.origin);url.searchParams.set('date',date.value);url.searchParams.set('timezone',zone.value);const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const data=await response.json();slots.innerHTML=data.slots.length?'':'<p class="empty-state">Nenhum horário disponível.</p>';data.slots.forEach(slot=>{const button=document.createElement('button');button.type='button';button.className='slot-button';button.textContent=slot.label;button.onclick=()=>{slots.querySelectorAll('button').forEach(b=>b.classList.remove('is-selected'));button.classList.add('is-selected');start.value=slot.start;submit.disabled=false;};slots.append(button);});}catch(e){slots.innerHTML='<p class="alert alert-danger" role="alert">Não foi possível carregar os horários.</p>';}}type.onchange=load;date.onchange=load;zone.onchange=load;})();</script>@endpush
