@extends('layouts.app')
@section('title', 'Faturas / Cobranças — IRCENTER')
@section('content')
@include('finance._nav')
<section class="page-heading"><div><div class="page-eyebrow"><span class="status-dot"></span>Financeiro</div><h1>Faturas / Cobranças</h1><p>Acompanhe emissão, vencimento, cobrança Efí e pagamento em uma única lista.</p></div>@if($financeEnabled&&auth()->user()->isAdministrator())<a class="button button-primary" href="{{ route('finance.invoices.create') }}">Nova cobrança avulsa</a>@endif</section>
@if(!$financeEnabled)<section class="panel finance-safety-panel"><div class="empty-state"><div><strong>Modo somente leitura</strong><span>FINANCE_ENABLED está desabilitado.</span></div></div></section>@endif
<section class="panel"><form class="filter-bar finance-filter-grid" method="GET">
<div class="filter-search"><x-icon name="search" size="18"/><input name="search" value="{{ $search }}" placeholder="Cliente, nº da fatura ou ID Efí"></div>
<select class="filter-select" name="status"><option value="all">Todos os status</option><option value="open" @selected($status==='open')>Aguardando pagamento</option><option value="paid" @selected($status==='paid')>Pago</option><option value="partially_paid" @selected($status==='partially_paid')>Pagamento parcial</option><option value="canceled" @selected($status==='canceled')>Cancelado</option></select>
<select class="filter-select" name="charge"><option value="all">Com ou sem cobrança</option><option value="with" @selected($chargeFilter==='with')>Possui cobrança</option><option value="without" @selected($chargeFilter==='without')>Sem cobrança</option></select>
<label class="filter-date">Emissão de<input class="filter-select" type="date" name="issued_from" value="{{ $issuedFrom }}"></label><label class="filter-date">até<input class="filter-select" type="date" name="issued_to" value="{{ $issuedTo }}"></label><label class="filter-date">Vencimento de<input class="filter-select" type="date" name="due_from" value="{{ $dueFrom }}"></label><label class="filter-date">até<input class="filter-select" type="date" name="due_to" value="{{ $dueTo }}"></label><button class="button button-secondary">Filtrar</button><a class="button button-ghost" href="{{ route('finance.invoices.index') }}">Limpar</a></form>
@if($invoices->isEmpty())<div class="empty-state empty-state-large"><div><strong>Nenhuma fatura encontrada</strong><span>Crie uma cobrança avulsa ou ajuste os filtros.</span></div></div>@else
<div class="table-responsive"><table class="data-table"><thead><tr><th>Nº / referência</th><th>Cliente</th><th>Status</th><th>Vencimento</th><th>Emissão</th><th>Valor</th><th>Cobrança Efí</th><th>Ações</th></tr></thead><tbody>
@foreach($invoices as $invoice)@php
$charge=$invoice->charges->first();$effective=$charge?->status ?: $invoice->status;
$label=match($effective){'paid'=>'Pago','overdue'=>'Vencido','canceled'=>'Cancelado','failed','submission_unknown','submitting'=>'Requer revisão','partially_paid'=>'Pagamento parcial',default=>'Aguardando pagamento'};
$class=match($effective){'paid'=>'is-active','failed','submission_unknown','submitting','overdue'=>'is-warning','canceled'=>'is-inactive',default=>'is-pending'};
@endphp<tr><td><a class="table-primary-link table-mono" href="{{ route('finance.invoices.show',$invoice) }}">#{{ $invoice->id }}</a><span class="table-secondary-text table-mono">{{ Str::limit($invoice->public_id,12) }}</span></td><td>{{ $invoice->client_trade_name_snapshot ?: $invoice->client_legal_name_snapshot }}</td><td><span class="status-pill {{ $class }}">{{ $label }}</span></td><td>{{ $invoice->due_on?->format('d/m/Y') }}</td><td>{{ $invoice->issued_on?->format('d/m/Y') }}</td><td><strong>R$ {{ number_format((float)$invoice->total,2,',','.') }}</strong></td><td>@if($charge)<span class="table-secondary-text">{{ $charge->provider==='efi'?'Efí':ucfirst($charge->provider) }}</span><span class="table-mono">{{ $charge->provider_charge_id ?: 'Processando' }}</span>@else<span class="table-secondary-text">Não emitida</span>@endif</td><td><details class="action-menu"><summary aria-label="Ações da fatura">•••</summary><div class="action-menu-content"><a href="{{ route('finance.invoices.show',$invoice) }}">Visualizar detalhes</a>@if($charge?->provider_billet_url)<a href="{{ $charge->provider_billet_url }}" target="_blank" rel="noopener">Abrir boleto</a>@endif @if($charge?->provider_billet_pdf_url)<a href="{{ $charge->provider_billet_pdf_url }}" target="_blank" rel="noopener">Baixar PDF</a>@endif @if($charge?->provider_pix_copy_paste)<button type="button" data-copy="{{ $charge->provider_pix_copy_paste }}">Copiar Pix</button>@endif<a href="{{ route('finance.invoices.create',['client_id'=>$invoice->core_client_id]) }}">Nova fatura relacionada</a></div></details></td></tr>@endforeach
</tbody></table></div><div class="pagination-simple">{{ $invoices->links() }}</div>@endif</section>
@endsection
