<?php
use App\Modules\Scheduling\Http\Controllers\{AdminSchedulingController,PublicSchedulingController}; use Illuminate\Support\Facades\Route;
Route::prefix('agenda')->name('scheduling.public.')->group(function():void{
 Route::get('/agendamento/{appointment}/confirmacao',[PublicSchedulingController::class,'confirmation'])->name('confirmation');
 Route::get('/agendamento/{appointment}/cancelar',[PublicSchedulingController::class,'cancelShow'])->middleware('throttle:scheduling-action')->name('cancel.show'); Route::post('/agendamento/{appointment}/cancelar',[PublicSchedulingController::class,'cancel'])->middleware('throttle:scheduling-action')->name('cancel');
 Route::get('/agendamento/{appointment}/reagendar',[PublicSchedulingController::class,'rescheduleShow'])->middleware('throttle:scheduling-action')->name('reschedule.show'); Route::get('/agendamento/{appointment}/reagendar/calendar',[PublicSchedulingController::class,'rescheduleCalendar'])->middleware('throttle:scheduling-availability')->name('reschedule.calendar'); Route::get('/agendamento/{appointment}/reagendar/availability',[PublicSchedulingController::class,'rescheduleAvailability'])->middleware('throttle:scheduling-availability')->name('reschedule.availability'); Route::post('/agendamento/{appointment}/reagendar',[PublicSchedulingController::class,'reschedule'])->middleware('throttle:scheduling-action')->name('reschedule');
 Route::get('/agendamento/{appointment}/calendario.ics',[PublicSchedulingController::class,'ics'])->name('ics');
 Route::get('/{eventType}/availability',[PublicSchedulingController::class,'availability'])->middleware('throttle:scheduling-availability')->name('availability'); Route::get('/{eventType}/calendar',[PublicSchedulingController::class,'calendar'])->middleware('throttle:scheduling-availability')->name('calendar'); Route::get('/{eventType}',[PublicSchedulingController::class,'show'])->name('show'); Route::post('/{eventType}',[PublicSchedulingController::class,'store'])->middleware('throttle:scheduling-booking')->name('store');
});
Route::middleware(['auth','user.active','password.changed'])->prefix('scheduling')->name('scheduling.admin.')->group(function():void{
 Route::get('/',[AdminSchedulingController::class,'index'])->name('index'); Route::get('/create',[AdminSchedulingController::class,'create'])->name('appointments.create'); Route::get('/event-types/{eventType}/availability',[AdminSchedulingController::class,'appointmentAvailability'])->name('appointments.availability'); Route::post('/appointments',[AdminSchedulingController::class,'storeAppointment'])->name('appointments.store'); Route::get('/export',[AdminSchedulingController::class,'export'])->name('export'); Route::get('/calendar/{view?}',[AdminSchedulingController::class,'calendar'])->whereIn('view',['day','week','month'])->name('calendar');
 Route::get('/event-types',[AdminSchedulingController::class,'eventTypes'])->name('event-types'); Route::post('/event-types',[AdminSchedulingController::class,'storeEventType'])->name('event-types.store'); Route::put('/event-types/{eventType}',[AdminSchedulingController::class,'updateEventType'])->name('event-types.update');
 Route::get('/availability/{eventType}',[AdminSchedulingController::class,'availability'])->name('availability'); Route::post('/availability/{eventType}/rules',[AdminSchedulingController::class,'storeRule'])->name('rules.store'); Route::delete('/availability/{eventType}/rules/{rule}',[AdminSchedulingController::class,'deleteRule'])->name('rules.delete'); Route::post('/availability/{eventType}/exceptions',[AdminSchedulingController::class,'storeException'])->name('exceptions.store'); Route::delete('/availability/{eventType}/exceptions/{exception}',[AdminSchedulingController::class,'deleteException'])->name('exceptions.delete');
 Route::get('/appointments/{appointment}',[AdminSchedulingController::class,'show'])->name('appointments.show'); Route::patch('/appointments/{appointment}',[AdminSchedulingController::class,'update'])->name('appointments.update');
});
