@extends('layouts.app')
@section('title', 'Financeiro — IRCENTER')
@section('content')
@include('finance._nav')
<section class="page-heading"><div><div class="page-eyebrow"><span class="status-dot"></span>Financeiro</div><h1>Visão geral</h1><p>O que está em aberto, pago e previsto para os clientes.</p></div><div class="page-actions">@if($financeEnabled&&auth()->user()->isAdministrator())<a class="button button-primary" href="{{ route('finance.invoices.create') }}">Nova cobrança avulsa</a><a class="button button-secondary" href="{{ route('finance.items.index') }}">Novo item</a>@endif<a class="button button-secondary" href="{{ route('finance.clients.index') }}">Ver clientes</a><a class="button button-secondary" href="{{ route('finance.invoices.index') }}">Ver faturas</a></div></section>
@if(!$financeEnabled)<section class="panel"><div class="empty-state"><div><strong>Módulo em modo protegido</strong><span>As consultas continuam disponíveis em modo somente leitura.</span></div></div></section>@endif
<section class="finance-overview-cards"><article><span>Em aberto</span><strong>R$ {{ number_format((float)$openInvoiceTotal,2,',','.') }}</strong></article><article><span>Pago no mês</span><strong>R$ {{ number_format((float)$paidInPeriod,2,',','.') }}</strong></article><article><span>Vencido</span><strong>R$ {{ number_format((float)$overdueTotal,2,',','.') }}</strong></article><article><span>Clientes com recorrência</span><strong>{{ $clientsRecurring }}</strong></article><article class="{{ $attentionCount>0?'requires-attention':'' }}"><span>Requer atenção</span><strong>{{ $attentionCount }}</strong></article></section>
<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Agenda</span><h2>Próximas cobranças</h2></div></header>@if($upcomingConfigurations->isEmpty())<div class="empty-state"><div><strong>Nenhuma recorrência ativa</strong><span>Configure uma cobrança recorrente em Clientes.</span></div></div>@else<div class="table-responsive"><table class="data-table"><thead><tr><th>Cliente</th><th>Item</th><th>Geração</th><th>Vencimento</th><th>Valor</th></tr></thead><tbody>@foreach($upcomingConfigurations as $contract)<tr><td><a href="{{ route('finance.clients.show',$contract->core_client_id) }}">{{ $contract->client_trade_name_snapshot ?: $contract->client_legal_name_snapshot }}</a></td><td>{{ $contract->items->first()?->description ?: 'Requer configuração' }}</td><td>Dia {{ $contract->generation_day }}</td><td>Dia {{ $contract->due_day }}</td><td>R$ {{ number_format($contract->items->sum(fn($item)=>(float)$item->quantity*(float)$item->unit_amount),2,',','.') }}</td></tr>@endforeach</tbody></table></div>@endif</section>
<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Movimentação</span><h2>Faturas recentes</h2></div></header>@if($recentInvoices->isEmpty())<div class="empty-state"><div><strong>Nenhuma fatura</strong><span>As faturas recentes aparecerão aqui.</span></div></div>@else<div class="table-responsive"><table class="data-table"><thead><tr><th>Cliente</th><th>Vencimento</th><th>Valor</th><th>Status</th></tr></thead><tbody>@foreach($recentInvoices as $invoice)@php($effective=$invoice->charges->first()?->status ?: $invoice->status)<tr><td><a href="{{ route('finance.invoices.show',$invoice) }}">{{ $invoice->client_trade_name_snapshot ?: $invoice->client_legal_name_snapshot }}</a></td><td>{{ $invoice->due_on?->format('d/m/Y') }}</td><td>R$ {{ number_format((float)$invoice->total,2,',','.') }}</td><td><span class="status-pill {{ $effective==='paid'?'is-active':(in_array($effective,['submission_unknown','failed','overdue'],true)?'is-warning':'is-pending') }}">{{ match($effective){'paid'=>'Pago','overdue'=>'Vencido','canceled'=>'Cancelado','submission_unknown','failed','submitting'=>'Requer atenção',default=>'Aguardando pagamento'} }}</span></td></tr>@endforeach</tbody></table></div>@endif</section>
@if(auth()->user()->isAdministrator())<details class="panel finance-technical"><summary>Detalhes técnicos</summary><div class="finance-technical-grid"><span>Provider: {{ $paymentProvider==='efi'?'Efí':$paymentProvider }}</span><span>Ambiente: {{ $efiEnvironment==='homologation'?'Homologação':$efiEnvironment }}</span><span>Automação: desligada</span></div></details>@endif
@endsection
