@extends('layouts.app')
@section('title', 'Financeiro — IRCENTER')
@section('content')
<section class="page-heading finance-workspace-heading"><div><div class="page-eyebrow"><span class="status-dot"></span>Operação financeira</div><h1>Financeiro</h1><p>Cliente, recorrência, cobranças e pagamentos em um só lugar.</p></div>@if($financeEnabled&&auth()->user()->isAdministrator())<a class="button button-primary" href="{{ route('finance.invoices.create') }}">+ Nova cobrança avulsa</a>@endif</section>
@if(!$financeEnabled)<section class="panel"><div class="empty-state"><div><strong>Módulo em modo protegido</strong><span>As consultas continuam disponíveis em modo somente leitura.</span></div></div></section>@endif
<section class="finance-overview-strip"><div><span>Em aberto</span><strong>R$ {{ number_format((float)$openTotal,2,',','.') }}</strong></div><div><span>Pago no mês</span><strong>R$ {{ number_format((float)$paidTotal,2,',','.') }}</strong></div><div><span>Vencido</span><strong>R$ {{ number_format((float)$overdueTotal,2,',','.') }}</strong></div><div class="{{ $attentionCount?'requires-attention':'' }}"><span>Requer atenção</span><strong>{{ $attentionCount }}</strong></div></section>
<div class="finance-workspace {{ $selectedClient?'has-selection':'' }}">
<aside class="finance-client-column"><div class="finance-client-column-header"><h2>Clientes</h2><form method="GET"><div class="filter-search"><x-icon name="search" size="18"/><input name="search" value="{{ $search }}" placeholder="Buscar cliente" aria-label="Buscar cliente"></div></form></div><div class="finance-client-list">
@forelse($clientRows as $row)<a class="finance-client-card {{ $selectedClient?->id===$row['client']->id?'is-selected':'' }}" href="{{ route('finance.dashboard',['client'=>$row['client']->id,'search'=>$search?:null]) }}"><strong>{{ $row['client']->displayName() }}</strong><span>{{ $row['current']?'R$ '.number_format($row['total'],2,',','.').' / mês':'Sem recorrência' }}</span><small>{{ $row['open_count'] }} {{ $row['open_count']===1?'cobrança em aberto':'cobranças em aberto' }}</small><em class="status-pill {{ $row['current']?->status==='active'?'is-active':'is-inactive' }}">{{ match($row['current']?->status){'active'=>'Ativa','suspended'=>'Suspensa',default=>'Sem recorrência'} }}</em></a>@empty<div class="empty-state"><div><strong>Nenhum cliente encontrado</strong><span>Ajuste a busca.</span></div></div>@endforelse
</div></aside>
<section class="finance-client-panel" aria-label="Financeiro do cliente">@if($selectedClient)
<a class="finance-mobile-back" href="{{ route('finance.dashboard') }}">← Voltar aos clientes</a>
<header class="finance-client-header"><div><span class="panel-eyebrow">Financeiro do cliente</span><h2>{{ $selectedClient->displayName() }}</h2></div><div class="page-actions">@if($financeEnabled&&auth()->user()->isAdministrator())<a class="button button-primary" href="{{ route('finance.invoices.create',['client_id'=>$selectedClient->id]) }}">Nova cobrança avulsa</a><a class="button button-secondary" href="{{ $primary?route('finance.contracts.edit',$primary):route('finance.contracts.create',['client_id'=>$selectedClient->id,'return_to_client'=>1]) }}">{{ $primary?'Editar recorrência':'Configurar recorrência' }}</a>@endif</div></header>
<div class="finance-client-summary"><div><span>Em aberto</span><strong>R$ {{ number_format((float)$clientOpenTotal,2,',','.') }}</strong></div><div><span>Pago no mês</span><strong>R$ {{ number_format((float)$clientPaidInMonth,2,',','.') }}</strong></div><div><span>Próximo vencimento</span><strong>{{ $nextDueOn ? date('d/m/Y', strtotime($nextDueOn)) : '—' }}</strong></div></div>
<section class="finance-workspace-section"><header><div><span class="panel-eyebrow">Cobrança recorrente</span><h3>{{ $primary?->items->first()?->description?:'Nenhuma cobrança recorrente configurada.' }}</h3></div>@if($primary)<span class="status-pill {{ $primary->status==='active'?'is-active':'is-inactive' }}">{{ $primary->status==='active'?'Ativa':'Suspensa' }}</span>@endif</header>
@if($primary)
@php $total=$primary->items->where('active',true)->sum(fn($item)=>(float)$item->quantity*(float)$item->unit_amount); @endphp
<div class="finance-recurring-grid"><div><span>Serviço</span><strong>{{ $primary->items->first()?->description?:'Requer configuração' }}</strong></div><div><span>Valor</span><strong>R$ {{ number_format($total,2,',','.') }} / mês</strong></div><div><span>Geração</span><strong>Gera todo dia {{ $primary->generation_day }}</strong></div><div><span>Vencimento</span><strong>Vence dia {{ $primary->due_day }}</strong></div><div><span>Forma de cobrança</span><strong>Boleto + Pix</strong></div><div><span>Destinatário</span><strong>{{ $recipient?:'Contato financeiro' }}</strong></div><div><span>Status</span><strong>{{ $primary->status==='active'?'Ativa':'Suspensa' }}</strong></div><div><span>Automação</span><strong>{{ $automationEnabled?'Ligada':'Desligada' }}</strong></div></div>@if($financeEnabled&&auth()->user()->isAdministrator())<div class="form-actions"><a class="button button-secondary" href="{{ route('finance.contracts.edit',$primary) }}">Editar</a></div>@endif
@else<div class="finance-empty-recurring"><p>Configure uma cobrança mensal para este cliente ou gere uma cobrança avulsa.</p>@if($financeEnabled&&auth()->user()->isAdministrator())<div class="page-actions"><a class="button button-primary" href="{{ route('finance.contracts.create',['client_id'=>$selectedClient->id,'return_to_client'=>1]) }}">Configurar recorrência</a><a class="button button-secondary" href="{{ route('finance.invoices.create',['client_id'=>$selectedClient->id]) }}">Nova cobrança avulsa</a></div>@endif</div>@endif</section>
@if($previous->isNotEmpty())<details class="finance-workspace-section finance-history"><summary>Configurações anteriores ({{ $previous->count() }})</summary><div class="table-responsive"><table class="data-table"><thead><tr><th>Período</th><th>Item</th><th>Valor</th><th>Geração</th><th>Vencimento</th><th>Status</th></tr></thead><tbody>@foreach($previous as $contract)<tr><td>{{ $contract->starts_on?->format('d/m/Y')?:'—' }} – {{ $contract->ends_on?->format('d/m/Y')?:'atual' }}</td><td>{{ $contract->items->first()?->description?:'Sem item' }}</td><td>R$ {{ number_format($contract->items->sum(fn($item)=>(float)$item->quantity*(float)$item->unit_amount),2,',','.') }}</td><td>Dia {{ $contract->generation_day }}</td><td>Dia {{ $contract->due_day }}</td><td>{{ match($contract->status){'active'=>'Ativa','suspended'=>'Suspensa','ended'=>'Encerrada',default=>'Inativa'} }}</td></tr>@endforeach</tbody></table></div></details>@endif
<section class="finance-workspace-section"><header><div><span class="panel-eyebrow">Cobranças</span><h3>Últimas cobranças</h3></div><a class="button button-ghost" href="{{ route('finance.invoices.index',['search'=>$selectedClient->client_code]) }}">Ver todas</a></header>@if($invoices->isEmpty())<div class="empty-state"><div><strong>Nenhuma cobrança</strong><span>As cobranças deste cliente aparecerão aqui.</span></div></div>@else<div class="table-responsive"><table class="data-table"><thead><tr><th>Nº</th><th>Vencimento</th><th>Valor</th><th>Status</th><th>Cobrança</th><th>Ações</th></tr></thead><tbody>
@foreach($invoices as $invoice)
@php
    $charge = $invoice->charges->first();
    $effective = $charge?->status ?: $invoice->status;
    $attention = in_array($effective, ['submission_unknown', 'failed', 'submitting'], true);
@endphp
<tr><td><a href="{{ route('finance.invoices.show',$invoice) }}">#{{ $invoice->id }}</a></td><td>{{ $invoice->due_on?->format('d/m/Y') }}</td><td><strong>R$ {{ number_format((float)$invoice->total,2,',','.') }}</strong></td><td><span class="status-pill {{ $effective==='paid'?'is-active':($attention||$effective==='overdue'?'is-warning':'is-pending') }}">{{ match($effective){'paid'=>'Pago','overdue'=>'Vencido','canceled'=>'Cancelado','submission_unknown','failed','submitting'=>'Requer atenção',default=>'Aguardando pagamento'} }}</span></td><td>{{ !$charge?'Não emitida':($attention?'Efí — requer confirmação':($charge->provider==='fake'?'Teste/Fake':'Efí'.($charge->provider_charge_id?' #'.$charge->provider_charge_id:''))) }}</td><td><details class="action-menu"><summary aria-label="Ações da cobrança">•••</summary><div class="action-menu-content"><a href="{{ route('finance.invoices.show',$invoice) }}">Ver detalhes</a>@if($charge?->provider_billet_url)<a href="{{ $charge->provider_billet_url }}" target="_blank" rel="noopener">Abrir boleto</a>@endif @if($charge?->provider_billet_pdf_url)<a href="{{ $charge->provider_billet_pdf_url }}" target="_blank" rel="noopener">Baixar PDF</a>@endif @if($charge?->provider_pix_copy_paste)<button type="button" data-copy="{{ $charge->provider_pix_copy_paste }}">Copiar Pix</button>@endif<a href="{{ route('finance.invoices.show',$invoice) }}#historico">Ver histórico</a>@if(auth()->user()->isAdministrator())<a href="{{ route('finance.invoices.create',['client_id'=>$selectedClient->id]) }}">Nova cobrança relacionada</a>@endif</div></details></td></tr>
@endforeach
</tbody></table></div>@endif</section>
@if(auth()->user()->isAdministrator())<details class="finance-workspace-section finance-technical"><summary>Detalhes técnicos</summary><div class="finance-technical-grid"><span>Provider: {{ $paymentProvider==='efi'?'Efí':$paymentProvider }}</span><span>Ambiente: {{ $efiEnvironment==='homologation'?'Homologação':$efiEnvironment }}</span><span>Automação: {{ $automationEnabled?'ligada':'desligada' }}</span></div></details>@endif
@else<div class="empty-state empty-state-large"><div><strong>Selecione um cliente</strong><span>O financeiro do cliente será exibido aqui.</span></div></div>@endif</section></div>
<nav class="finance-secondary-nav"><a href="{{ route('finance.invoices.index') }}">Todas as cobranças</a><a href="{{ route('finance.items.index') }}">Itens de cobrança</a></nav>
@endsection
