@push('scripts')
<script nonce="{{ request()->attributes->get('csp_nonce') }}">
(()=>{
 const calendar=document.querySelector('#booking-calendar'),slots=document.querySelector('#booking-slots'),zone=document.querySelector('#booking-timezone'),form=document.querySelector('#booking-form'),start=document.querySelector('#selected-start'),selectedZone=document.querySelector('#selected-timezone'),label=document.querySelector('#month-label'),times=document.querySelector('#booking-times'),dateLabel=document.querySelector('#selected-date-label'),picker=document.querySelector('#booking-picker'),formPanel=document.querySelector('#booking-form-panel'),back=document.querySelector('#booking-back'),contextSelection=document.querySelector('#context-selection'),contextDatetime=document.querySelector('#context-datetime'),contextTimezone=document.querySelector('#context-timezone');
 let month=new Date(),selected=null,selectedButton=null,selectedSlot=null;month.setDate(1);
 const calendarUrl=@json($calendarUrl),availabilityUrl=@json($availabilityUrl),token=@json($token),formMode=@json($formMode ?? false);
 const monthKey=()=>month.getFullYear()+'-'+String(month.getMonth()+1).padStart(2,'0');
 const fullDate=date=>new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
 const setContext=()=>{if(!selectedSlot||!contextSelection)return;contextSelection.hidden=false;contextDatetime.textContent=fullDate(selected)+' às '+selectedSlot.label;if(contextTimezone)contextTimezone.textContent=zone.value;};
 function chooseSlot(button,slot){selectedSlot=slot;slots.querySelectorAll('.slot-row').forEach(row=>row.classList.remove('is-selected'));slots.querySelectorAll('.slot-button').forEach(item=>item.setAttribute('aria-pressed','false'));button.setAttribute('aria-pressed','true');button.closest('.slot-row').classList.add('is-selected');start.value=slot.start;selectedZone.value=zone.value;setContext();}
 async function selectDate(button,date){selected=date;selectedButton=button;selectedSlot=null;start.value='';calendar.querySelectorAll('.calendar-date').forEach(item=>{item.classList.remove('is-selected');item.setAttribute('aria-selected','false');});button.classList.add('is-selected');button.setAttribute('aria-selected','true');times.hidden=false;dateLabel.textContent=fullDate(date);slots.innerHTML='<p class="loading-state" role="status">Carregando horários…</p>';try{const url=new URL(availabilityUrl,location.origin);url.searchParams.set('date',date);url.searchParams.set('timezone',zone.value);if(token)url.searchParams.set('token',token);const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const data=await response.json();slots.innerHTML=data.slots.length?'':'<p class="empty-state">Os horários deste dia acabaram de ficar indisponíveis. Escolha outra data.</p>';data.slots.forEach(slot=>{const row=document.createElement('div');row.className='slot-row';const button=document.createElement('button');button.type='button';button.className='slot-button';button.textContent=slot.label;button.setAttribute('aria-label','Selecionar '+slot.label);button.setAttribute('aria-pressed','false');button.onclick=()=>chooseSlot(button,slot);const advance=document.createElement('button');advance.type='button';advance.className='button button-primary slot-advance';advance.textContent=formMode?'Avançar':'Confirmar novo horário';advance.onclick=()=>{chooseSlot(button,slot);if(formMode){picker.hidden=true;formPanel.hidden=false;document.querySelector('#guest_name').focus();}else form.requestSubmit();};row.append(button,advance);slots.append(row);});}catch(e){slots.innerHTML='<p class="alert alert-danger" role="alert">Não foi possível carregar os horários. Tente novamente.</p>';}}
 async function loadCalendar(){calendar.setAttribute('aria-busy','true');calendar.innerHTML='<p class="loading-state" role="status">Carregando calendário…</p>';label.textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(month);try{const url=new URL(calendarUrl,location.origin);url.searchParams.set('month',monthKey());url.searchParams.set('timezone',zone.value);if(token)url.searchParams.set('token',token);const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const data=await response.json();calendar.innerHTML='';const first=new Date(month.getFullYear(),month.getMonth(),1).getDay();for(let i=0;i<first;i++){const spacer=document.createElement('span');spacer.className='calendar-spacer';calendar.append(spacer);}Object.entries(data.days).forEach(([date,status])=>{const button=document.createElement('button');button.type='button';button.className='calendar-date status-'+status;button.dataset.date=date;button.disabled=status!=='available';button.textContent=String(Number(date.slice(-2)));const today=new Date().toLocaleDateString('en-CA',{timeZone:zone.value});if(date===today)button.setAttribute('aria-current','date');button.setAttribute('aria-label',fullDate(date)+(status==='available'?' — disponível':' — indisponível'));button.onclick=()=>selectDate(button,date);calendar.append(button);});}catch(e){calendar.innerHTML='<p class="alert alert-danger" role="alert">Não foi possível carregar o calendário. Tente novamente.</p>';}finally{calendar.setAttribute('aria-busy','false');}}
 document.querySelector('#month-prev').onclick=()=>{month.setMonth(month.getMonth()-1);selected=null;times.hidden=true;loadCalendar();};document.querySelector('#month-next').onclick=()=>{month.setMonth(month.getMonth()+1);selected=null;times.hidden=true;loadCalendar();};zone.onchange=()=>{selected=null;selectedSlot=null;times.hidden=true;start.value='';if(contextSelection)contextSelection.hidden=true;loadCalendar();};
 if(back)back.onclick=()=>{formPanel.hidden=true;picker.hidden=false;if(selectedButton)selectedButton.focus();};
 if(formMode&&formPanel&&!formPanel.hidden){picker.hidden=true;const oldStart=start.value;if(oldStart){const parsed=new Date(oldStart);selected=parsed.toLocaleDateString('en-CA',{timeZone:zone.value});selectedSlot={start:oldStart,label:parsed.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:zone.value})};setContext();}}
 loadCalendar();
})();
</script>
@endpush
