@extends('scheduling.public.layout')
@section('title','Reagendar — Agenda IRCENTER')
@section('content')
<section class="booking-shell"><aside class="booking-service"><span class="eyebrow">Reagendamento IRCENTER</span><h1>{{ $appointment->eventType->name }}</h1><dl><div><dt>Participante</dt><dd>{{ $appointment->guest_name }}</dd></div><div><dt>Horário atual</dt><dd>{{ $appointment->scheduled_start_at->setTimezone($appointment->timezone)->format('d/m/Y H:i') }}</dd></div></dl></aside>
 <div class="booking-picker" id="booking-picker"><div class="booking-calendar-panel"><h2>Selecione uma nova data</h2><div class="calendar-toolbar"><button type="button" class="calendar-nav" id="month-prev" aria-label="Mês anterior">←</button><strong id="month-label" aria-live="polite"></strong><button type="button" class="calendar-nav" id="month-next" aria-label="Próximo mês">→</button></div><div class="calendar-weekdays" aria-hidden="true"><span>seg</span><span>ter</span><span>qua</span><span>qui</span><span>sex</span><span>sáb</span><span>dom</span></div><div id="booking-calendar" class="public-calendar" aria-label="Calendário de disponibilidade" aria-busy="true"><p>Carregando calendário…</p></div><div class="calendar-status-legend" aria-label="Legenda do calendário"><span class="legend-available">Disponível</span><span class="legend-unavailable">Indisponível</span></div></div><aside class="booking-times" id="booking-times" aria-labelledby="slots-title" hidden><h2 id="slots-title">Horários disponíveis</h2><p id="selected-date-label" class="selected-date-label"></p><div id="booking-slots" class="booking-slots" aria-live="polite"></div></aside></div>
 <form method="post" id="booking-form" hidden>@csrf<input type="hidden" name="token" value="{{ $token }}"><input type="hidden" name="start" id="selected-start"><input type="hidden" name="timezone" id="selected-timezone" value="{{ $timezone }}">@if($errors->any())<div class="alert alert-danger" role="alert">{{ $errors->first() }}</div>@endif</form>
</section>
@endsection
@include('scheduling.public.calendar-script',['calendarUrl'=>route('scheduling.public.reschedule.calendar',$appointment),'availabilityUrl'=>route('scheduling.public.reschedule.availability',$appointment),'token'=>$token,'formMode'=>false])
