<?php
namespace Tests\Feature\Scheduling;
use App\Modules\Scheduling\Actions\CreateAppointment; use App\Modules\Scheduling\Models\{Appointment,AvailabilityRule,EventType}; use App\Modules\Scheduling\Services\SlotGenerator; use App\Models\User; use Carbon\CarbonImmutable; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Notification; use Illuminate\Validation\ValidationException; use Tests\TestCase;
class SchedulingFlowTest extends TestCase {use RefreshDatabase;
 protected function setUp():void{parent::setUp();config(['scheduling.enabled'=>true,'scheduling.default_timezone'=>'America/Sao_Paulo']);Notification::fake();}
 private function type():EventType{$type=EventType::create(['name'=>'Consultoria Técnica','slug'=>'consultoria-tecnica','duration_minutes'=>60,'slot_interval_minutes'=>15,'location_type'=>'online','buffer_before_minutes'=>0,'buffer_after_minutes'=>0,'minimum_notice_minutes'=>0,'maximum_days_ahead'=>90,'active'=>true]);AvailabilityRule::create(['event_type_id'=>$type->id,'day_of_week'=>1,'start_time'=>'09:00','end_time'=>'12:00','timezone'=>'America/Sao_Paulo','active'=>true]);return$type;}
 public function test_public_module_is_hidden_when_disabled():void{config(['scheduling.enabled'=>false]);$this->get('/agenda/anything')->assertNotFound();}
 public function test_slot_generator_respects_duration_and_booking():void{$type=$this->type();$now=CarbonImmutable::parse('2026-09-06 12:00','UTC');$slots=app(SlotGenerator::class)->generate($type,'2026-09-07','America/Sao_Paulo',$now);$this->assertSame(['09:00','09:15','09:30','09:45','10:00','10:15','10:30','10:45','11:00'],array_column($slots,'label'));Appointment::create(['event_type_id'=>$type->id,'scheduled_start_at'=>'2026-09-07 13:30:00','scheduled_end_at'=>'2026-09-07 14:30:00','timezone'=>'America/Sao_Paulo','status'=>'confirmed','guest_name'=>'Ada','guest_email'=>'ada@example.test','cancellation_token_hash'=>str_repeat('a',64),'reschedule_token_hash'=>str_repeat('b',64)]);$slots=app(SlotGenerator::class)->generate($type,'2026-09-07','America/Sao_Paulo',$now);$this->assertNotContains('10:30',array_column($slots,'label'));}
 public function test_only_one_attempt_can_book_same_slot():void{$type=$this->type();CarbonImmutable::setTestNow(CarbonImmutable::parse('2026-09-06 12:00','UTC'));$data=['start'=>'2026-09-07T09:00:00-03:00','timezone'=>'America/Sao_Paulo','guest_name'=>'Ada','guest_email'=>'ada@example.test'];app(CreateAppointment::class)->execute($type,$data);$this->expectException(ValidationException::class);app(CreateAppointment::class)->execute($type,$data);}
 public function test_viewer_reads_but_cannot_edit():void{$type=$this->type();$viewer=User::factory()->create(['role'=>User::ROLE_VIEWER,'active'=>true,'must_change_password'=>false]);$this->actingAs($viewer)->get(route('scheduling.admin.event-types'))->assertOk();$this->actingAs($viewer)->post(route('scheduling.admin.event-types.store'),[])->assertForbidden();}
}
