<?php
namespace App\Modules\Scheduling\Http\Controllers;
use App\Http\Controllers\Controller; use App\Models\Client; use App\Modules\Scheduling\Actions\CreateAppointment; use App\Modules\Scheduling\Models\{Appointment,AppointmentEvent,AvailabilityException,AvailabilityRule,EventType}; use App\Modules\Scheduling\Services\{SchedulingAudit,SlotGenerator}; use Carbon\CarbonImmutable; use Illuminate\Http\{JsonResponse,RedirectResponse,Request,StreamedResponse}; use Illuminate\View\View;
final class AdminSchedulingController extends Controller {
 private function operate(Request $r):void{abort_unless($r->user()->canOperate(),403);}
 private function query(Request $r){return Appointment::query()->with(['eventType','client'])->when($r->filled('status'),fn($q)=>$q->where('status',$r->string('status')))->when($r->filled('event_type'),fn($q)=>$q->where('event_type_id',$r->integer('event_type')))->when($r->filled('from'),fn($q)=>$q->where('scheduled_start_at','>=',$r->date('from')->startOfDay()))->when($r->filled('to'),fn($q)=>$q->where('scheduled_start_at','<=',$r->date('to')->endOfDay()))->when($r->filled('search'),fn($q)=>$q->where(fn($q)=>$q->where('guest_name','like','%'.$r->string('search').'%')->orWhere('guest_email','like','%'.$r->string('search').'%')));}
 public function index(Request $r):View{$now=now();return view('scheduling.admin.index',['today'=>Appointment::whereDate('scheduled_start_at',$now->toDateString())->count(),'nextSeven'=>Appointment::whereBetween('scheduled_start_at',[$now,$now->copy()->addDays(7)])->whereIn('status',['scheduled','confirmed'])->count(),'cancelled'=>Appointment::where('status','cancelled')->whereMonth('cancelled_at',$now->month)->count(),'noShow'=>Appointment::where('status','no_show')->count(),'appointments'=>$this->query($r)->orderBy('scheduled_start_at')->paginate(20)->withQueryString(),'eventTypes'=>EventType::orderBy('name')->get()]);}
 public function create(Request $r):View{$this->operate($r);return view('scheduling.admin.create',['eventTypes'=>EventType::where('active',true)->orderBy('name')->get(),'clients'=>Client::where('active',true)->orderBy('legal_name')->get(),'timezone'=>config('scheduling.default_timezone')]);}
 public function appointmentAvailability(Request $r,EventType $eventType,SlotGenerator $slots):JsonResponse{$this->operate($r);$d=$r->validate(['date'=>['required','date_format:Y-m-d'],'timezone'=>['required','timezone']]);return response()->json(['slots'=>$slots->generate($eventType,$d['date'],$d['timezone'])]);}
 public function storeAppointment(Request $r,CreateAppointment $create):RedirectResponse{$this->operate($r);$d=$r->validate(['event_type_id'=>['required','exists:scheduling_event_types,id'],'start'=>['required','date'],'timezone'=>['required','timezone'],'guest_name'=>['required','string','max:120'],'guest_email'=>['required','email:rfc','max:255'],'guest_phone'=>['nullable','string','max:40'],'guest_company'=>['nullable','string','max:120'],'notes'=>['nullable','string','max:2000'],'client_id'=>['nullable','exists:clients,id']]);$type=EventType::where('active',true)->findOrFail($d['event_type_id']);$result=$create->execute($type,$d,$r->user()->id);return redirect()->route('scheduling.admin.appointments.show',$result['appointment'])->with('status','Agendamento criado.');}
 public function calendar(Request $r,string $view='week'):View{$start=match($view){'day'=>CarbonImmutable::parse($r->query('date','today'))->startOfDay(),'month'=>CarbonImmutable::parse($r->query('date','today'))->startOfMonth(),default=>CarbonImmutable::parse($r->query('date','today'))->startOfWeek()};$end=match($view){'day'=>$start->endOfDay(),'month'=>$start->endOfMonth(),default=>$start->endOfWeek()};return view('scheduling.admin.calendar',['mode'=>$view,'start'=>$start,'end'=>$end,'appointments'=>Appointment::with('eventType')->whereBetween('scheduled_start_at',[$start,$end])->orderBy('scheduled_start_at')->get()->groupBy(fn($a)=>$a->scheduled_start_at->format('Y-m-d'))]);}
 public function eventTypes():View{return view('scheduling.event-types.index',['eventTypes'=>EventType::with('host')->orderBy('name')->get(),'users'=>\App\Models\User::where('active',true)->orderBy('name')->get()]);}
 public function storeEventType(Request $r,SchedulingAudit $audit):RedirectResponse{$this->operate($r);$d=$this->eventData($r);$d['created_by']=$r->user()->id;$e=EventType::create($d);$audit->record('event_type.created',$e->id,$r->user()->id);return back()->with('status','Tipo de agendamento criado.');}
 public function updateEventType(Request $r,EventType $eventType,SchedulingAudit $audit):RedirectResponse{$this->operate($r);$eventType->update($this->eventData($r));$audit->record('event_type.updated',$eventType->id,$r->user()->id);return back()->with('status','Tipo atualizado.');}
 private function eventData(Request $r):array{return $r->validate(['name'=>['required','string','max:120'],'slug'=>['required','alpha_dash','max:120','unique:scheduling_event_types,slug,'.($r->route('eventType')?->id??'NULL')],'description'=>['nullable','string','max:2000'],'duration_minutes'=>['required','integer','between:15,480'],'slot_interval_minutes'=>['required','integer','between:5,120'],'buffer_before_minutes'=>['required','integer','between:0,240'],'buffer_after_minutes'=>['required','integer','between:0,240'],'minimum_notice_minutes'=>['required','integer','between:0,43200'],'maximum_days_ahead'=>['required','integer','between:1,730'],'location_type'=>['required','in:online,phone,in_person,custom'],'location_value'=>['nullable','string','max:255'],'host_user_id'=>['nullable','exists:users,id'],'active'=>['nullable','boolean']])+['active'=>$r->boolean('active')];}
 public function availability(EventType $eventType):View{return view('scheduling.availability.index',['eventType'=>$eventType,'rules'=>$eventType->rules()->orderBy('day_of_week')->orderBy('start_time')->get(),'exceptions'=>$eventType->exceptions()->orderByDesc('date')->get()]);}
 public function storeRule(Request $r,EventType $eventType,SchedulingAudit $audit):RedirectResponse{$this->operate($r);$d=$r->validate(['day_of_week'=>['required','integer','between:1,7'],'start_time'=>['required','date_format:H:i'],'end_time'=>['required','date_format:H:i','after:start_time'],'timezone'=>['required','timezone']]);$eventType->rules()->create($d+['active'=>true]);$audit->record('availability.updated',$eventType->id,$r->user()->id);return back()->with('status','Janela adicionada.');}
 public function deleteRule(Request $r,EventType $eventType,AvailabilityRule $rule,SchedulingAudit $audit):RedirectResponse{$this->operate($r);abort_unless($rule->event_type_id===$eventType->id,404);$id=$rule->id;$rule->delete();$audit->record('availability.rule.deleted',$eventType->id,$r->user()->id,['rule_id'=>$id]);return back()->with('status','Janela removida.');}
 public function storeException(Request $r,EventType $eventType,SchedulingAudit $audit):RedirectResponse{$this->operate($r);$d=$r->validate(['date'=>['required','date'],'start_time'=>['nullable','date_format:H:i','required_with:end_time'],'end_time'=>['nullable','date_format:H:i','after:start_time','required_with:start_time'],'type'=>['required','in:unavailable,available_override'],'reason'=>['nullable','string','max:255']]);$exception=$eventType->exceptions()->create($d+['created_by'=>$r->user()->id]);$audit->record('availability.exception.created',$eventType->id,$r->user()->id,['exception_id'=>$exception->id,'date'=>$d['date'],'type'=>$d['type']]);return back()->with('status','Exceção cadastrada.');}
 public function deleteException(Request $r,EventType $eventType,AvailabilityException $exception,SchedulingAudit $audit):RedirectResponse{$this->operate($r);abort_unless($exception->event_type_id===$eventType->id,404);$values=['exception_id'=>$exception->id,'date'=>$exception->date->format('Y-m-d'),'type'=>$exception->type];$exception->delete();$audit->record('availability.exception.deleted',$eventType->id,$r->user()->id,$values);return back()->with('status','Exceção removida.');}
 public function show(Appointment $appointment):View{return view('scheduling.admin.show',['appointment'=>$appointment->load(['eventType','client','events']),'clients'=>Client::where('active',true)->orderBy('legal_name')->get()]);}
 public function update(Request $r,Appointment $appointment,SchedulingAudit $audit):RedirectResponse{$this->operate($r);$d=$r->validate(['status'=>['nullable','in:scheduled,confirmed,cancelled,completed,no_show'],'client_id'=>['nullable','exists:clients,id']]);if(isset($d['status'])){$d['cancelled_at']=$d['status']==='cancelled'?now():null;$d['completed_at']=$d['status']==='completed'?now():null;AppointmentEvent::create(['appointment_id'=>$appointment->id,'event_type'=>$d['status'],'metadata'=>[],'actor_type'=>'user','actor_id'=>$r->user()->id,'created_at'=>now()]);$audit->record('appointment.'.$d['status'],$appointment->id,$r->user()->id);}$appointment->update($d);return back()->with('status','Agendamento atualizado.');}
 public function export(Request $r):StreamedResponse{return response()->streamDownload(function()use($r){$out=fopen('php://output','w');fputcsv($out,['Data','Visitante','Email','Serviço','Status']);$this->query($r)->orderBy('scheduled_start_at')->each(function($a)use($out){$safe=fn($v)=>preg_match('/^[=+\-@]/',(string)$v)?"'".$v:$v;fputcsv($out,[$a->scheduled_start_at->toIso8601String(),$safe($a->guest_name),$safe($a->guest_email),$safe($a->eventType->name),$a->statusLabel()]);});fclose($out);},'agendamentos.csv',['Content-Type'=>'text/csv; charset=UTF-8']);}
}
