<?php
namespace App\Modules\Scheduling\Http\Controllers;
use App\Http\Controllers\Controller; use App\Modules\Scheduling\Actions\{CancelAppointment,CreateAppointment,RescheduleAppointment}; use App\Modules\Scheduling\Models\{Appointment,EventType}; use App\Modules\Scheduling\Services\{IcsGenerator,SlotGenerator}; use Illuminate\Http\{JsonResponse,RedirectResponse,Request,Response}; use Illuminate\View\View; use Illuminate\Validation\Rule;
final class PublicSchedulingController extends Controller {
 private function enabled():void{abort_unless(config('scheduling.enabled'),404);}
 public function show(EventType $eventType,Request $r):View{$this->enabled();abort_unless($eventType->active,404);return view('scheduling.public.book',['eventType'=>$eventType,'timezone'=>$r->query('timezone',config('scheduling.default_timezone'))]);}
 public function availability(EventType $eventType,Request $r,SlotGenerator $slots):JsonResponse{$this->enabled();abort_unless($eventType->active,404);$data=$r->validate(['date'=>['required','date_format:Y-m-d'],'timezone'=>['required','timezone']]);return response()->json(['date'=>$data['date'],'timezone'=>$data['timezone'],'slots'=>$slots->generate($eventType,$data['date'],$data['timezone'])]);}
 public function store(EventType $eventType,Request $r,CreateAppointment $create):RedirectResponse{$this->enabled();abort_unless($eventType->active,404);$data=$r->validate(['start'=>['required','date'],'timezone'=>['required','timezone'],'guest_name'=>['required','string','max:120'],'guest_email'=>['required','email:rfc','max:255'],'guest_phone'=>['nullable','string','max:40'],'guest_company'=>['nullable','string','max:120'],'notes'=>['nullable','string','max:2000'],'website'=>['nullable','size:0'],'form_started_at'=>['required','integer']]);if(time()-(int)$data['form_started_at']<2)return back()->withErrors(['guest_name'=>'Envio rápido demais. Tente novamente.'])->withInput();$result=$create->execute($eventType,$data);return redirect()->route('scheduling.public.confirmation',$result['appointment']);}
 public function confirmation(Appointment $appointment):View{$this->enabled();return view('scheduling.public.confirmation',['appointment'=>$appointment->load('eventType')]);}
 public function cancelShow(Appointment $appointment,Request $r):View{$this->enabled();return view('scheduling.public.cancel',compact('appointment'));}
 public function cancel(Appointment $appointment,Request $r,CancelAppointment $cancel):RedirectResponse{$this->enabled();$data=$r->validate(['token'=>['required','string','size:64']]);$cancel->execute($appointment,$data['token']);return redirect()->route('scheduling.public.confirmation',$appointment)->with('status','Agendamento cancelado.');}
 public function rescheduleShow(Appointment $appointment,Request $r):View{$this->enabled();return view('scheduling.public.reschedule',['appointment'=>$appointment->load('eventType'),'token'=>$r->query('token'),'timezone'=>$appointment->timezone]);}
 public function reschedule(Appointment $appointment,Request $r,RescheduleAppointment $action):RedirectResponse{$this->enabled();$data=$r->validate(['token'=>['required','string','size:64'],'start'=>['required','date'],'timezone'=>['required','timezone']]);$action->execute($appointment,$data['token'],$data['start'],$data['timezone']);return redirect()->route('scheduling.public.confirmation',$appointment)->with('status','Agendamento reagendado.');}
 public function ics(Appointment $appointment,IcsGenerator $ics):Response{$this->enabled();return response($ics->generate($appointment),200,['Content-Type'=>'text/calendar; charset=utf-8','Content-Disposition'=>'attachment; filename="agendamento.ics"']);}
}
