@extends('layouts.app')
@section('title', 'Fiscal — IRCENTER')
@section('content')
<section class="page-heading"><div><div class="page-eyebrow"><span class="status-dot"></span>Fiscal</div><h1>NFS-e e documentos fiscais</h1><p>Preparação e registro assistido de emissões realizadas no Portal Nacional.</p></div><div class="page-actions"><span class="status-pill is-pending">Modo de emissão: Manual</span>@if(auth()->user()->isAdministrator())<a class="button button-primary" href="{{ route('fiscal.documents.create') }}">Novo documento fiscal</a>@endif</div></section>
<section class="finance-overview-cards"><article><span>Rascunhos</span><strong>{{ $draftCount }}</strong></article><article><span>Prontos para emissão</span><strong>{{ $readyCount }}</strong></article><article><span>Emitidos</span><strong>{{ $authorizedCount }}</strong></article><article class="{{ $pendingCount ? 'requires-attention' : '' }}"><span>Pendências</span><strong>{{ $pendingCount }}</strong></article></section>
<section class="panel"><form method="GET" class="form-grid"><label class="form-field"><span>Cliente</span><input name="search" value="{{ $filters['search'] }}"></label><label class="form-field"><span>Status</span><select name="status"><option value="">Todos</option>@foreach(['draft'=>'Rascunho','ready'=>'Pronto para emissão','authorized'=>'Emitida','cancelled'=>'Cancelado internamente'] as $value=>$label)<option value="{{ $value }}" @selected($filters['status']===$value)>{{ $label }}</option>@endforeach</select></label><label class="form-field"><span>Competência inicial</span><input type="month" name="competence" value="{{ $filters['competence'] }}"></label><label class="form-field"><span>Competência final</span><input type="month" name="competence_to" value="{{ $filters['competenceTo'] }}"></label><label class="form-field"><span>Origem</span><select name="origin"><option value="">Todas</option><option value="manual" @selected($filters['origin']==='manual')>Registro manual</option><option value="provider" @selected($filters['origin']==='provider')>Integração</option></select></label><div class="page-actions"><button class="button button-secondary">Filtrar</button><a class="button button-secondary" href="{{ route('fiscal.dashboard') }}">Limpar</a></div></form></section>
<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Operação manual</span><h2>Documentos fiscais</h2></div></header>
@if($documents->isEmpty())<div class="empty-state"><div><strong>Nenhum documento fiscal encontrado para os filtros selecionados.</strong><span>Limpe os filtros ou crie um rascunho para iniciar a preparação manual.</span></div></div>@else<div class="table-responsive"><table class="data-table"><thead><tr><th>Cliente</th><th>Competência</th><th>NFS-e</th><th>Valor</th><th>Status</th><th>Origem</th><th>Atualização</th><th>Ações</th></tr></thead><tbody>@foreach($documents as $document)<tr><td>{{ $clientNames[$document->core_client_id] ?? 'Cliente' }}</td><td>{{ $document->competence_date->format('m/Y') }}</td><td class="table-mono">{{ $document->nfse_number ?: 'Ainda não emitida' }}</td><td>R$ {{ number_format((float)$document->net_amount,2,',','.') }}</td><td>{{ ['draft'=>'Rascunho','ready'=>'Pronto para emissão','processing'=>'Processando','authorized'=>'Emitida','rejected'=>'Rejeitada','cancelled'=>'Cancelado internamente'][$document->status->value] ?? $document->status->value }}</td><td>{{ $document->emission_origin === 'manual' ? 'Registro manual' : 'Integração' }}</td><td>{{ $document->updated_at->format('d/m/Y H:i') }}</td><td><a class="inline-link" href="{{ route('fiscal.documents.show',$document) }}">Abrir</a></td></tr>@endforeach</tbody></table></div>{{ $documents->links() }}@endif</section>
@endsection
