@extends('layouts.app')
@section('title', 'Novo documento fiscal — IRCENTER')
@section('content')
<section class="page-heading"><div><div class="page-eyebrow"><a class="inline-link" href="{{ route('fiscal.dashboard') }}">Fiscal</a> · Novo documento</div><h1>Novo documento fiscal</h1><p>Crie um rascunho interno para revisar antes da emissão no Portal Nacional.</p></div></section>
@if($errors->any())<div class="alert-error" role="alert">{{ $errors->first() }}</div>@endif
@if(!$issuer)<div class="alert-error" role="alert">Cadastre e ative um emitente fiscal antes de criar documentos.</div>@else
<form method="POST" action="{{ route('fiscal.documents.store') }}" class="panel form-panel">@csrf
<input type="hidden" name="issuer_id" value="{{ $issuer->id }}">
<div class="form-grid">
<label class="form-field"><span>Cliente</span><select id="client_id" name="client_id" required aria-describedby="client-fiscal-status"><option value="">Selecione</option>@foreach($clients as $client)@php($profile=$profiles->get($client->id))@php($missing=collect(['document','legal_name','municipality','municipality_code','state'])->filter(fn($field)=>blank($profile?->{$field}))->count())<option value="{{ $client->id }}" data-document="{{ $profile?->document }}" data-missing="{{ $missing }}" data-edit-url="{{ route('clients.fiscal.edit',$client) }}" @selected((string)old('client_id',$selectedClientId)===(string)$client->id)>{{ $client->displayName() }}</option>@endforeach</select></label>
<div class="form-field" id="client-fiscal-status" aria-live="polite"><span>Cadastro fiscal</span><strong id="client-status-text">Selecione um cliente</strong><small id="client-document"></small><a id="client-edit-link" class="inline-link" hidden>Editar dados fiscais</a></div>
<label class="form-field"><span>Serviço</span><select id="service_id" name="service_id" required aria-describedby="service-fiscal-status"><option value="">Selecione</option>@foreach($services as $service)<option value="{{ $service->id }}" data-description="{{ $service->fiscal_description }}" data-code="{{ $service->national_service_code }}" data-value="{{ $service->billingItem?->default_amount }}">{{ $service->fiscal_description }}</option>@endforeach</select></label>
<div class="form-field" id="service-fiscal-status" aria-live="polite"><span>Cadastro fiscal do serviço</span><strong id="service-status-text">Selecione um serviço</strong><small id="service-details"></small></div>
<label class="form-field"><span>Competência</span><input type="date" name="competence_date" value="{{ old('competence_date',now()->toDateString()) }}" required></label>
<label class="form-field details-card-wide"><span>Descrição do serviço</span><textarea id="description" name="description" required aria-invalid="{{ $errors->has('description') ? 'true' : 'false' }}">{{ old('description') }}</textarea></label>
<label class="form-field"><span>Valor do serviço</span><input id="unit_amount" name="unit_amount" inputmode="decimal" value="{{ old('unit_amount') }}" required></label>
<details class="details-card-wide"><summary>Informações opcionais</summary><div class="form-grid"><label class="form-field"><span>Data da prestação <small>(opcional)</small></span><input type="date" name="service_date" value="{{ old('service_date') }}"></label><label class="form-field"><span>Quantidade</span><input name="quantity" inputmode="decimal" value="{{ old('quantity','1.0000') }}" required></label><label class="form-field"><span>Desconto</span><input name="discount_amount" inputmode="decimal" value="{{ old('discount_amount','0.00') }}"></label><label class="form-field"><span>Dedução</span><input name="deduction_amount" inputmode="decimal" value="{{ old('deduction_amount','0.00') }}"></label><label class="form-field details-card-wide"><span>Observações internas <small>(opcional)</small></span><textarea name="summary">{{ old('summary') }}</textarea></label></div><p>Vínculos financeiros não são necessários para criar o rascunho e podem ser associados por fluxos administrativos quando aplicável.</p></details>
</div><div class="page-actions"><button class="button button-primary">Criar rascunho</button><a class="button button-secondary" href="{{ route('fiscal.dashboard') }}">Cancelar</a></div></form>
<script nonce="{{ request()->attributes->get('csp_nonce') }}">
const client=document.getElementById('client_id'),service=document.getElementById('service_id');
function updateClient(){const option=client.options[client.selectedIndex],missing=Number(option?.dataset.missing);document.getElementById('client-status-text').textContent=!option?.value?'Selecione um cliente':missing===0?'Completo':`${missing} pendência${missing===1?'':'s'}`;document.getElementById('client-document').textContent=option?.dataset.document?`CPF/CNPJ: ${option.dataset.document}`:'';const link=document.getElementById('client-edit-link');link.hidden=!option?.value;link.href=option?.dataset.editUrl||'#';}
function updateService(){const option=service.options[service.selectedIndex],code=option?.dataset.code;document.getElementById('service-status-text').textContent=!option?.value?'Selecione um serviço':code?'Completo':'Falta o código de serviço nacional';document.getElementById('service-details').textContent=code?`Código do serviço: ${code}`:'';if(option?.dataset.description&&!document.getElementById('description').value)document.getElementById('description').value=option.dataset.description;if(option?.dataset.value&&!document.getElementById('unit_amount').value)document.getElementById('unit_amount').value=option.dataset.value;}
client.addEventListener('change',updateClient);service.addEventListener('change',updateService);updateClient();updateService();
</script>
@endif
@endsection
