@extends('layouts.app')
@section('title', 'Novo documento fiscal — IRCENTER')
@section('content')
<section class="page-heading"><div><div class="page-eyebrow">Fiscal</div><h1>Novo documento fiscal</h1><p>Crie um rascunho interno para revisar antes da emissão no Portal Nacional.</p></div></section>
@if($errors->any())<div class="alert-error">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('fiscal.documents.store') }}" class="panel form-panel">@csrf<div class="form-grid">
<label class="form-field"><span>Cliente</span><select name="client_id" required><option value="">Selecione</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected((string)old('client_id',$selectedClientId)===(string)$client->id)>{{ $client->displayName() }}</option>@endforeach</select></label>
<label class="form-field"><span>Emitente</span><select name="issuer_id" required>@foreach($issuers as $issuer)<option value="{{ $issuer->id }}">{{ $issuer->legal_name }}</option>@endforeach</select></label>
<label class="form-field"><span>Serviço fiscal</span><select id="service_id" name="service_id" required><option value="">Selecione</option>@foreach($services as $service)<option value="{{ $service->id }}" data-description="{{ $service->fiscal_description }}">{{ $service->fiscal_description }} · {{ $service->national_service_code ?: 'sem classificação' }}</option>@endforeach</select></label>
<label class="form-field"><span>Competência</span><input type="date" name="competence_date" value="{{ old('competence_date',now()->toDateString()) }}" required></label><label class="form-field"><span>Data da prestação</span><input type="date" name="service_date" value="{{ old('service_date') }}"></label>
<label class="form-field details-card-wide"><span>Descrição do serviço</span><textarea id="description" name="description" required>{{ old('description') }}</textarea></label><label class="form-field"><span>Quantidade</span><input name="quantity" value="{{ old('quantity','1.0000') }}" required></label><label class="form-field"><span>Valor unitário</span><input name="unit_amount" value="{{ old('unit_amount') }}" required></label><label class="form-field"><span>Desconto</span><input name="discount_amount" value="{{ old('discount_amount','0.00') }}"></label><label class="form-field"><span>Dedução</span><input name="deduction_amount" value="{{ old('deduction_amount','0.00') }}"></label><label class="form-field details-card-wide"><span>Observações internas</span><textarea name="summary">{{ old('summary') }}</textarea></label>
<details class="details-card-wide"><summary>Vínculos opcionais com o Financeiro</summary><div class="form-grid">@foreach(['billing_contract_id'=>'ID do contrato','invoice_id'=>'ID da fatura','charge_id'=>'ID da cobrança','billing_item_id'=>'ID do item financeiro'] as $field=>$label)<label class="form-field"><span>{{ $label }}</span><input type="number" name="{{ $field }}" value="{{ old($field) }}"></label>@endforeach</div></details>
</div><div class="page-actions"><button class="button button-primary">Criar rascunho</button><a class="button button-secondary" href="{{ route('fiscal.dashboard') }}">Cancelar</a></div></form>
<script nonce="{{ request()->attributes->get('csp_nonce') }}">document.getElementById('service_id').addEventListener('change',function(){const option=this.options[this.selectedIndex];if(option.dataset.description&&!document.getElementById('description').value)document.getElementById('description').value=option.dataset.description;});</script>
@endsection
