@extends('layouts.app')
@section('title', 'Documento fiscal — IRCENTER')
@section('content')
@php($status=$document->status->value)
<section class="page-heading"><div><div class="page-eyebrow"><a class="inline-link" href="{{ route('fiscal.dashboard') }}">Fiscal</a> · Documento</div><h1>{{ $document->nfse_number ? 'NFS-e '.$document->nfse_number : 'Documento fiscal' }}</h1><p>{{ match($status){'draft'=>'Complete os dados para preparar a emissão.','ready'=>'Documento pronto. Emita a NFS-e no Portal Nacional e depois registre o resultado aqui.','authorized'=>'NFS-e registrada como autorizada.','cancelled'=>'Documento cancelado internamente. Nenhuma operação foi enviada ao governo.',default=>'Acompanhe o documento fiscal.'} }}</p></div><span class="status-pill {{ $status==='authorized'?'is-active':($status==='cancelled'?'is-inactive':'is-pending') }}">{{ ['draft'=>'Rascunho','ready'=>'Pronto para emissão','processing'=>'Processando','authorized'=>'Emitida','rejected'=>'Rejeitada','cancelled'=>'Cancelado internamente'][$status] ?? $status }}</span></section>
@if(session('success'))<div class="alert-success" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert-error" role="alert">{{ $errors->first() }}</div>@endif
@php($readinessLabels=['READY'=>['Pronto para emissão','Todos os dados obrigatórios estão preenchidos.'],'WARNING'=>['Pode emitir','Há informações opcionais pendentes.'],'BLOCKED'=>['Existem dados obrigatórios faltando','Resolva as pendências antes de marcar como pronto.']])
<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Prontidão · {{ $readiness->status }}</span><h2>{{ $readinessLabels[$readiness->status][0] }}</h2><p>{{ $readinessLabels[$readiness->status][1] }}</p></div></header>@foreach($readiness->issues as $issue)<p><strong>{{ $issue['level']==='BLOCKED' ? 'Obrigatório' : 'Opcional' }} · {{ $issue['area'] }}</strong> — {{ $issue['message'] }} @if(str_starts_with($issue['code'],'customer.'))<a class="inline-link" href="{{ route('clients.fiscal.edit',$document->core_client_id) }}">Editar dados fiscais</a>@endif</p>@endforeach
@if(auth()->user()->isAdministrator()&&$status==='draft')<div class="page-actions"><form method="POST" action="{{ route('fiscal.documents.ready',$document) }}">@csrf<p>Ao continuar, os dados serão congelados para emissão manual. Nenhuma NFS-e será enviada ao governo.</p><button class="button button-primary" @disabled($readiness->isBlocked())>Marcar como pronto para emissão</button></form><form method="POST" action="{{ route('fiscal.documents.cancel',$document) }}">@csrf<button class="button button-secondary">Cancelar rascunho</button></form></div>@elseif(auth()->user()->isAdministrator()&&$status==='ready')<form method="POST" action="{{ route('fiscal.documents.draft',$document) }}">@csrf<button class="button button-secondary">Voltar para revisão</button></form>@endif</section>
@php($issuer=$document->issuer_snapshot ?: $document->issuer->snapshot()) @php($customer=$document->customer_snapshot ?: $document->customer->snapshot()) @php($services=$document->service_snapshot ?: $document->items->map(fn($item)=>['description'=>$item->description,'quantity'=>$item->quantity,'unit_amount'=>$item->unit_amount,'total_amount'=>$item->total_amount,'classification'=>$item->service?->snapshot()])->all()) @php($values=$document->values_snapshot ?: $document->only(['services_amount','discount_amount','deduction_amount','withholding_amount','net_amount','currency']))
<section class="details-grid"><article class="panel details-card"><header class="panel-header"><h2>Emitente</h2></header><dl class="details-list"><div><dt>Razão social</dt><dd>{{ $issuer['legal_name'] }}</dd></div><div><dt>CNPJ</dt><dd class="table-mono">{{ $issuer['document'] }}</dd></div><div><dt>Inscrição municipal</dt><dd>{{ $issuer['municipal_registration'] ?: '—' }}</dd></div></dl></article>
<article class="panel details-card"><header class="panel-header"><h2>Tomador</h2></header><dl class="details-list"><div><dt>Nome / razão social</dt><dd>{{ $customer['legal_name'] ?: '—' }}</dd></div><div><dt>CPF/CNPJ</dt><dd class="table-mono">{{ $customer['document'] ?: '—' }}</dd></div><div><dt>Endereço</dt><dd>{{ collect([$customer['street'],$customer['address_number'],$customer['district']])->filter()->implode(', ') ?: '—' }}</dd></div><div><dt>Município / UF</dt><dd>{{ collect([$customer['municipality'],$customer['state']])->filter()->implode(' / ') ?: '—' }}</dd></div><div><dt>E-mail</dt><dd>{{ $customer['fiscal_email'] ?: '—' }}</dd></div></dl></article>
<article class="panel details-card details-card-wide"><header class="panel-header"><div><span class="panel-eyebrow">Portal Nacional</span><h2>Dados para emissão no Portal Nacional</h2></div>@if($status==='ready')<a class="button button-secondary" href="{{ $portalUrl }}" target="_blank" rel="noopener noreferrer">Abrir Portal Nacional da NFS-e</a>@endif</header><h3>Tomador</h3><p>Nome/Razão Social: {{ $customer['legal_name'] ?: '—' }}<br>CPF/CNPJ: <span class="table-mono">{{ $customer['document'] ?: '—' }}</span><br>E-mail: {{ $customer['fiscal_email'] ?: '—' }}<br>Município/UF: {{ $customer['municipality'] ?: '—' }}/{{ $customer['state'] ?: '—' }}</p><h3>Serviço</h3>@foreach($services as $service)<p>Descrição: {{ $service['description'] }}<br>Código do serviço: {{ data_get($service,'classification.national_service_code','—') }}</p>@endforeach<h3>Competência</h3><p>{{ $document->competence_date->format('d/m/Y') }}</p><h3>Valores</h3><p>Valor do serviço: R$ {{ number_format((float)$values['services_amount'],2,',','.') }}<br>Desconto: R$ {{ number_format((float)$values['discount_amount'],2,',','.') }}<br>Valor líquido: R$ {{ number_format((float)$values['net_amount'],2,',','.') }}</p>@if($document->summary)<h3>Dados complementares</h3><p>{{ $document->summary }}</p>@endif<div class="page-actions"><button type="button" class="button button-secondary" data-copy="{{ $customer['document'] }}">Copiar CPF/CNPJ</button><button type="button" class="button button-secondary" data-copy="{{ collect($services)->pluck('description')->implode('; ') }}">Copiar descrição</button><button type="button" class="button button-secondary" data-copy="{{ number_format((float)$values['services_amount'],2,',','.') }}">Copiar valor</button><button type="button" class="button button-secondary" id="copy-fiscal-summary">Copiar resumo para emissão</button></div><span id="copy-feedback" role="status" aria-live="polite"></span><textarea id="fiscal-summary" hidden>TOMADOR
Nome/Razão Social: {{ $customer['legal_name'] }}
CPF/CNPJ: {{ $customer['document'] }}
E-mail: {{ $customer['fiscal_email'] ?: 'Não informado' }}
Município/UF: {{ $customer['municipality'] }}/{{ $customer['state'] }}

SERVIÇO
Descrição: {{ collect($services)->pluck('description')->implode('; ') }}
Código do serviço: {{ collect($services)->pluck('classification.national_service_code')->filter()->implode('; ') ?: 'Não informado' }}

COMPETÊNCIA
{{ $document->competence_date->format('d/m/Y') }}

VALORES
Valor do serviço: R$ {{ number_format((float)$values['services_amount'],2,',','.') }}
Desconto: R$ {{ number_format((float)$values['discount_amount'],2,',','.') }}
Valor líquido: R$ {{ number_format((float)$values['net_amount'],2,',','.') }}</textarea></article></section>
@if($status==='ready'&&auth()->user()->isAdministrator())<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Registro manual</span><h2>Registrar NFS-e emitida</h2><p>A nota já deve ter sido emitida no Portal Nacional. Esta ação apenas registra o resultado no IRCENTER.</p></div></header><form method="POST" action="{{ route('fiscal.documents.authorize-manual',$document) }}">@csrf<div class="form-grid"><label class="form-field"><span>Número da NFS-e</span><input name="nfse_number" required></label><label class="form-field"><span>Chave de acesso <small>(opcional)</small></span><input name="access_key"></label><label class="form-field"><span>Código de verificação <small>(opcional)</small></span><input name="verification_code"></label><label class="form-field"><span>Data/hora de emissão</span><input type="datetime-local" name="authorized_at" required></label><label class="form-field details-card-wide"><span>Observação <small>(opcional)</small></span><textarea name="manual_authorization_notes"></textarea></label></div><label><input type="checkbox" name="confirmation" value="1" required> Confirmo que esta NFS-e foi emitida e autorizada no Portal Nacional.</label><div class="page-actions"><button class="button button-primary">Registrar NFS-e emitida</button></div></form></section>@endif
@if($status==='authorized')<section class="panel"><header class="panel-header"><h2>NFS-e registrada</h2></header><p>Número: <strong>{{ $document->nfse_number }}</strong> · Chave: <span class="table-mono">{{ $document->access_key ?: '—' }}</span> · Autorizada em {{ $document->authorized_at->format('d/m/Y H:i') }} · Origem manual</p><p>Cancelamento da NFS-e ainda não está disponível no IRCENTER.</p></section>
<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Arquivos privados</span><h2>Documentos anexados</h2><p>XML e PDF são opcionais após o registro da emissão.</p></div></header><form method="POST" enctype="multipart/form-data" action="{{ route('fiscal.documents.artifacts.store',$document) }}">@csrf<div class="form-grid"><label class="form-field"><span>Tipo</span><select name="type"><option value="manual_nfse_xml">XML da NFS-e</option><option value="manual_danfse_pdf">PDF/DANFSe</option></select></label><label class="form-field"><span>Arquivo</span><input type="file" name="artifact" accept=".xml,application/xml,.pdf,application/pdf" required></label></div><button class="button button-secondary">Anexar arquivo privado</button></form>@forelse($document->artifacts as $artifact)<div class="page-actions"><span><strong>{{ $artifact->type === 'manual_nfse_xml' ? 'XML da NFS-e' : 'PDF/DANFSe' }}</strong> · {{ $artifact->original_filename }} · {{ number_format($artifact->size/1024,1,',','.') }} KB · enviado em {{ $artifact->created_at->format('d/m/Y H:i') }}</span><a class="button button-secondary" href="{{ route('fiscal.documents.artifacts.download',[$document,$artifact]) }}">Baixar</a><form method="POST" action="{{ route('fiscal.documents.artifacts.destroy',[$document,$artifact]) }}">@csrf @method('DELETE')<button class="button button-secondary">Remover</button></form></div>@empty<p>Nenhum documento anexado.</p>@endforelse</section>@endif
@php($timelineLabels=['fiscal.document.created'=>'Documento criado','fiscal.document.ready'=>'Marcado como pronto','fiscal.document.returned_to_draft'=>'Voltou para rascunho','fiscal.document.manual_authorized'=>'Emissão manual registrada','fiscal.document.internal_cancelled'=>'Rascunho cancelado internamente','fiscal.artifact.uploaded'=>'Documento anexado','fiscal.artifact.removed'=>'Documento anexado removido'])
<section class="panel"><header class="panel-header"><h2>Histórico</h2></header>@forelse($timeline->filter(fn($event)=>isset($timelineLabels[$event->action])) as $event)<p>{{ $event->created_at->format('d/m/Y H:i') }} — {{ $timelineLabels[$event->action] }}</p>@empty<p>Nenhum evento registrado.</p>@endforelse</section>
<details class="panel"><summary>Detalhes técnicos</summary><p>Ambiente: Homologação · Origem operacional: {{ $document->emission_origin === 'manual' ? 'Registro manual' : 'Integração' }} · Referência interna: {{ $document->public_id }}</p></details>
<script nonce="{{ request()->attributes->get('csp_nonce') }}">async function copyFiscalText(value){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(value)}else{const field=document.createElement('textarea');field.value=value;field.setAttribute('readonly','');field.style.position='fixed';field.style.opacity='0';document.body.appendChild(field);field.select();if(!document.execCommand('copy'))throw new Error('copy');field.remove()}document.getElementById('copy-feedback').textContent='Copiado.'}catch(error){document.getElementById('copy-feedback').textContent='Não foi possível copiar. Selecione e copie o texto manualmente.'}}document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',()=>copyFiscalText(button.dataset.copy)));document.getElementById('copy-fiscal-summary')?.addEventListener('click',()=>copyFiscalText(document.getElementById('fiscal-summary').value));</script>
@endsection
