@extends('layouts.app')
@section('title', 'Documento fiscal — IRCENTER')
@section('content')
@php($status=$document->status->value)
<section class="page-heading"><div><div class="page-eyebrow">Fiscal · {{ $document->public_id }}</div><h1>{{ $document->nfse_number ? 'NFS-e '.$document->nfse_number : 'Documento fiscal' }}</h1><p>{{ match($status){'draft'=>'Complete os dados para preparar a emissão.','ready'=>'Documento pronto. Emita a NFS-e no Portal Nacional e depois registre o resultado aqui.','authorized'=>'NFS-e registrada como autorizada.','cancelled'=>'Rascunho cancelado internamente. Nenhum cancelamento foi enviado ao governo.',default=>'Acompanhe o processamento do documento.'} }}</p></div><span class="status-pill {{ $status==='authorized'?'is-active':($status==='cancelled'?'is-inactive':'is-pending') }}">{{ ['draft'=>'Rascunho','ready'=>'Pronto','authorized'=>'Emitido','cancelled'=>'Cancelado'][$status] ?? $status }}</span></section>
@if(session('success'))<div class="alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert-error">{{ $errors->first() }}</div>@endif
<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Prontidão</span><h2>{{ $readiness->status }}</h2></div></header>@foreach($readiness->issues as $issue)<p><strong>{{ $issue['level'] }}</strong> — {{ $issue['message'] }}</p>@endforeach
@if(auth()->user()->isAdministrator()&&$status==='draft')<div class="page-actions"><form method="POST" action="{{ route('fiscal.documents.ready',$document) }}">@csrf<button class="button button-primary">Marcar pronto para emissão</button></form><form method="POST" action="{{ route('fiscal.documents.cancel',$document) }}">@csrf<button class="button button-secondary">Cancelar rascunho</button></form></div>@elseif(auth()->user()->isAdministrator()&&$status==='ready')<form method="POST" action="{{ route('fiscal.documents.draft',$document) }}">@csrf<button class="button button-secondary">Voltar para revisão</button></form>@endif</section>
@php($issuer=$document->issuer_snapshot ?: $document->issuer->snapshot()) @php($customer=$document->customer_snapshot ?: $document->customer->snapshot()) @php($services=$document->service_snapshot ?: $document->items->map(fn($item)=>['description'=>$item->description,'quantity'=>$item->quantity,'unit_amount'=>$item->unit_amount,'total_amount'=>$item->total_amount,'classification'=>$item->service?->snapshot()])->all()) @php($values=$document->values_snapshot ?: $document->only(['services_amount','discount_amount','deduction_amount','withholding_amount','net_amount','currency']))
<section class="details-grid"><article class="panel details-card"><header class="panel-header"><h2>Emitente</h2></header><dl class="details-list"><div><dt>Razão social</dt><dd>{{ $issuer['legal_name'] }}</dd></div><div><dt>CNPJ</dt><dd class="table-mono">{{ $issuer['document'] }}</dd></div><div><dt>Inscrição municipal</dt><dd>{{ $issuer['municipal_registration'] ?: '—' }}</dd></div></dl></article>
<article class="panel details-card"><header class="panel-header"><h2>Tomador</h2></header><dl class="details-list"><div><dt>Nome / razão social</dt><dd>{{ $customer['legal_name'] ?: '—' }}</dd></div><div><dt>CPF/CNPJ</dt><dd class="table-mono">{{ $customer['document'] ?: '—' }}</dd></div><div><dt>Endereço</dt><dd>{{ collect([$customer['street'],$customer['address_number'],$customer['district']])->filter()->implode(', ') ?: '—' }}</dd></div><div><dt>Município / UF</dt><dd>{{ collect([$customer['municipality'],$customer['state']])->filter()->implode(' / ') ?: '—' }}</dd></div><div><dt>E-mail</dt><dd>{{ $customer['fiscal_email'] ?: '—' }}</dd></div></dl></article>
<article class="panel details-card details-card-wide"><header class="panel-header"><div><span class="panel-eyebrow">Portal Nacional</span><h2>Dados para emissão manual</h2></div>@if($status==='ready')<a class="button button-secondary" href="{{ $portalUrl }}" target="_blank" rel="noopener noreferrer">Abrir Portal Nacional da NFS-e</a>@endif</header>@foreach($services as $service)<p><strong>Serviço:</strong> {{ $service['description'] }}<br><strong>Classificação:</strong> {{ data_get($service,'classification.national_service_code','—') }}<br><strong>Município:</strong> {{ data_get($service,'classification.municipality','—') }}</p>@endforeach<p><strong>Competência:</strong> {{ $document->competence_date->format('d/m/Y') }}<br><strong>Valor:</strong> R$ {{ number_format((float)$values['services_amount'],2,',','.') }} · <strong>Líquido:</strong> R$ {{ number_format((float)$values['net_amount'],2,',','.') }}</p><button type="button" class="button button-secondary" id="copy-fiscal-summary">Copiar resumo para emissão</button><textarea id="fiscal-summary" hidden>EMITENTE: {{ $issuer['legal_name'] }} | CNPJ: {{ $issuer['document'] }}
TOMADOR: {{ $customer['legal_name'] }} | CPF/CNPJ: {{ $customer['document'] }} | {{ $customer['municipality'] }}/{{ $customer['state'] }}
SERVIÇO: {{ collect($services)->pluck('description')->implode('; ') }}
COMPETÊNCIA: {{ $document->competence_date->format('d/m/Y') }} | VALOR: {{ $values['services_amount'] }} | LÍQUIDO: {{ $values['net_amount'] }}</textarea></article></section>
@if($status==='ready'&&auth()->user()->isAdministrator())<section class="panel"><header class="panel-header"><div><span class="panel-eyebrow">Registro manual</span><h2>Registrar NFS-e emitida</h2></div></header><form method="POST" action="{{ route('fiscal.documents.authorize-manual',$document) }}">@csrf<div class="form-grid"><label class="form-field"><span>Número da NFS-e</span><input name="nfse_number" required></label><label class="form-field"><span>Chave de acesso</span><input name="access_key"></label><label class="form-field"><span>Código de verificação</span><input name="verification_code"></label><label class="form-field"><span>Data/hora de autorização</span><input type="datetime-local" name="authorized_at" required></label><label class="form-field details-card-wide"><span>Observação interna</span><textarea name="manual_authorization_notes"></textarea></label></div><label><input type="checkbox" name="confirmation" value="1" required> Confirmo que esta NFS-e foi emitida e autorizada no Portal Nacional.</label><div class="page-actions"><button class="button button-primary">Registrar NFS-e emitida</button></div></form></section>@endif
@if($status==='authorized')<section class="panel"><header class="panel-header"><h2>NFS-e registrada</h2></header><p>Número: <strong>{{ $document->nfse_number }}</strong> · Chave: <span class="table-mono">{{ $document->access_key ?: '—' }}</span> · Autorizada em {{ $document->authorized_at->format('d/m/Y H:i') }} · Origem manual</p><p>Cancelamento da NFS-e ainda não está disponível no IRCENTER.</p></section>
<section class="panel"><header class="panel-header"><h2>Artifacts</h2></header><form method="POST" enctype="multipart/form-data" action="{{ route('fiscal.documents.artifacts.store',$document) }}">@csrf<div class="form-grid"><label class="form-field"><span>Tipo</span><select name="type"><option value="manual_nfse_xml">XML oficial</option><option value="manual_danfse_pdf">DANFSe/PDF oficial</option></select></label><label class="form-field"><span>Arquivo</span><input type="file" name="artifact" required></label></div><button class="button button-secondary">Anexar arquivo privado</button></form>@foreach($document->artifacts as $artifact)<div class="page-actions"><span>{{ $artifact->type }} · {{ $artifact->original_filename }} · {{ number_format($artifact->size/1024,1,',','.') }} KB · <span class="table-mono">{{ substr($artifact->sha256,0,12) }}…</span></span><a class="button button-secondary" href="{{ route('fiscal.documents.artifacts.download',[$document,$artifact]) }}">Download</a><form method="POST" action="{{ route('fiscal.documents.artifacts.destroy',[$document,$artifact]) }}">@csrf @method('DELETE')<button class="button button-secondary">Remover</button></form></div>@endforeach</section>@endif
<section class="panel"><header class="panel-header"><h2>Timeline</h2></header>@forelse($timeline as $event)<p>{{ $event->created_at->format('d/m/Y H:i') }} — {{ ['fiscal.document.created'=>'Rascunho criado','fiscal.document.ready'=>'Documento pronto para emissão','fiscal.document.returned_to_draft'=>'Documento devolvido para revisão','fiscal.document.manual_authorized'=>'NFS-e registrada manualmente','fiscal.document.internal_cancelled'=>'Rascunho cancelado internamente','fiscal.artifact.uploaded'=>'Artefato anexado','fiscal.artifact.removed'=>'Artefato removido'][$event->action] ?? $event->action }}</p>@empty<p>Nenhum evento registrado.</p>@endforelse</section>
<details class="panel"><summary>Detalhes técnicos</summary><p>Ambiente: Homologação · Provider: {{ $document->provider }} · Origem: {{ $document->emission_origin }} · ID: {{ $document->public_id }}</p></details>
<script nonce="{{ request()->attributes->get('csp_nonce') }}">document.getElementById('copy-fiscal-summary')?.addEventListener('click',()=>navigator.clipboard.writeText(document.getElementById('fiscal-summary').value));</script>
@endsection
